/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./api/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  InOrOutEnum: "IN" | "OUT"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Any: any
  Date: any
}

export interface NexusGenObjects {
  AccessToken: { // root type
    accessToken?: string | null; // String
    item_id?: string | null; // String
    request_id?: string | null; // String
  }
  Account: { // root type
    account_id?: string | null; // String
    balances?: NexusGenRootTypes['Balances'] | null; // Balances
    mask?: string | null; // String
    name?: string | null; // String
    official_name?: string | null; // String
    subtype?: string | null; // String
    type?: string | null; // String
  }
  Balances: { // root type
    available?: number | null; // Float
    current?: number | null; // Float
    iso_currency_code?: string | null; // String
    limit?: number | null; // Float
    unofficial_currency_code?: string | null; // String
  }
  Counterparty: { // root type
    confidence_level?: string | null; // String
    entity_id?: string | null; // String
    logo_url?: string | null; // String
    name?: string | null; // String
    type?: string | null; // String
    website?: string | null; // String
  }
  Item: { // root type
    auth_method?: string | null; // String
    available_products?: Array<string | null> | null; // [String]
    billed_products?: Array<string | null> | null; // [String]
    consent_expiration_time?: string | null; // String
    error?: string | null; // String
    institution_id?: string | null; // String
    institution_name?: string | null; // String
    item_id?: string | null; // String
    update_type?: string | null; // String
    webhook?: string | null; // String
  }
  LinkToken: { // root type
    expiration?: string | null; // String
    link_token?: string | null; // String
    request_id?: string | null; // String
  }
  Location: { // root type
    address?: string | null; // String
    city?: string | null; // String
    country?: string | null; // String
    lat?: number | null; // Float
    lon?: number | null; // Float
    postal_code?: string | null; // String
    region?: string | null; // String
    store_number?: string | null; // String
  }
  Mutation: {};
  PaymentMeta: { // root type
    by_order_of?: string | null; // String
    payee?: string | null; // String
    payer?: string | null; // String
    payment_method?: string | null; // String
    payment_processor?: string | null; // String
    ppd_id?: string | null; // String
    reason?: string | null; // String
    reference_number?: string | null; // String
  }
  PersonalFinanceCategory: { // root type
    confidence_level?: string | null; // String
    detailed?: string | null; // String
    primary?: string | null; // String
  }
  Query: {};
  Transaction: { // root type
    accountName: string; // String!
    amount: number; // Float!
    category?: string | null; // String
    date: number; // Int!
    id: number; // Int!
    io: NexusGenEnums['InOrOutEnum']; // InOrOutEnum!
    name: string; // String!
    reference?: string | null; // String
    senderOrRecipientName: string; // String!
    userId: number; // Int!
  }
  TransactionRes: { // root type
    accounts?: Array<NexusGenRootTypes['Account'] | null> | null; // [Account]
    item?: NexusGenRootTypes['Item'] | null; // Item
    request_id?: string | null; // String
    total_transactions?: number | null; // Int
    transactions?: Array<NexusGenRootTypes['Transaction'] | null> | null; // [Transaction]
  }
  User: { // root type
    email: string; // String!
    firstName?: string | null; // String
    id: number; // Int!
    lastName?: string | null; // String
    password?: string | null; // String
    phone?: string | null; // String
    transactions: Array<NexusGenRootTypes['Transaction'] | null>; // [Transaction]!
    uid: string; // String!
    username: string; // String!
  }
  uid: { // root type
    uid: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AccessToken: { // field return type
    accessToken: string | null; // String
    item_id: string | null; // String
    request_id: string | null; // String
  }
  Account: { // field return type
    account_id: string | null; // String
    balances: NexusGenRootTypes['Balances'] | null; // Balances
    mask: string | null; // String
    name: string | null; // String
    official_name: string | null; // String
    subtype: string | null; // String
    type: string | null; // String
  }
  Balances: { // field return type
    available: number | null; // Float
    current: number | null; // Float
    iso_currency_code: string | null; // String
    limit: number | null; // Float
    unofficial_currency_code: string | null; // String
  }
  Counterparty: { // field return type
    confidence_level: string | null; // String
    entity_id: string | null; // String
    logo_url: string | null; // String
    name: string | null; // String
    type: string | null; // String
    website: string | null; // String
  }
  Item: { // field return type
    auth_method: string | null; // String
    available_products: Array<string | null> | null; // [String]
    billed_products: Array<string | null> | null; // [String]
    consent_expiration_time: string | null; // String
    error: string | null; // String
    institution_id: string | null; // String
    institution_name: string | null; // String
    item_id: string | null; // String
    update_type: string | null; // String
    webhook: string | null; // String
  }
  LinkToken: { // field return type
    expiration: string | null; // String
    link_token: string | null; // String
    request_id: string | null; // String
  }
  Location: { // field return type
    address: string | null; // String
    city: string | null; // String
    country: string | null; // String
    lat: number | null; // Float
    lon: number | null; // Float
    postal_code: string | null; // String
    region: string | null; // String
    store_number: string | null; // String
  }
  Mutation: { // field return type
    createLinkToken: NexusGenRootTypes['LinkToken'] | null; // LinkToken
    createUser: NexusGenRootTypes['User']; // User!
    deleteUser: NexusGenRootTypes['User']; // User!
    emailSignIn: NexusGenRootTypes['User']; // User!
    exchangePublicToken: NexusGenRootTypes['AccessToken'] | null; // AccessToken
    get_balance: NexusGenScalars['Any'] | null; // Any
    get_transaction_data: NexusGenScalars['Any'] | null; // Any
    seedTransactions: boolean; // Boolean!
    updateUserDetails: NexusGenRootTypes['User']; // User!
  }
  PaymentMeta: { // field return type
    by_order_of: string | null; // String
    payee: string | null; // String
    payer: string | null; // String
    payment_method: string | null; // String
    payment_processor: string | null; // String
    ppd_id: string | null; // String
    reason: string | null; // String
    reference_number: string | null; // String
  }
  PersonalFinanceCategory: { // field return type
    confidence_level: string | null; // String
    detailed: string | null; // String
    primary: string | null; // String
  }
  Query: { // field return type
    allTransactions: NexusGenRootTypes['Transaction'][]; // [Transaction!]!
    fetchAccessTokenFromUser: NexusGenRootTypes['AccessToken'] | null; // AccessToken
    getTransactionById: NexusGenRootTypes['Transaction']; // Transaction!
    getTransactionsByUserId: Array<NexusGenRootTypes['Transaction'] | null>; // [Transaction]!
    getuseruidfromuserid: NexusGenRootTypes['uid'] | null; // uid
    user: NexusGenRootTypes['User']; // User!
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  Transaction: { // field return type
    accountName: string; // String!
    amount: number; // Float!
    category: string | null; // String
    date: number; // Int!
    id: number; // Int!
    io: NexusGenEnums['InOrOutEnum']; // InOrOutEnum!
    name: string; // String!
    reference: string | null; // String
    senderOrRecipientName: string; // String!
    userId: number; // Int!
  }
  TransactionRes: { // field return type
    accounts: Array<NexusGenRootTypes['Account'] | null> | null; // [Account]
    item: NexusGenRootTypes['Item'] | null; // Item
    request_id: string | null; // String
    total_transactions: number | null; // Int
    transactions: Array<NexusGenRootTypes['Transaction'] | null> | null; // [Transaction]
  }
  User: { // field return type
    email: string; // String!
    firstName: string | null; // String
    id: number; // Int!
    lastName: string | null; // String
    password: string | null; // String
    phone: string | null; // String
    transactions: Array<NexusGenRootTypes['Transaction'] | null>; // [Transaction]!
    uid: string; // String!
    username: string; // String!
  }
  uid: { // field return type
    uid: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AccessToken: { // field return type name
    accessToken: 'String'
    item_id: 'String'
    request_id: 'String'
  }
  Account: { // field return type name
    account_id: 'String'
    balances: 'Balances'
    mask: 'String'
    name: 'String'
    official_name: 'String'
    subtype: 'String'
    type: 'String'
  }
  Balances: { // field return type name
    available: 'Float'
    current: 'Float'
    iso_currency_code: 'String'
    limit: 'Float'
    unofficial_currency_code: 'String'
  }
  Counterparty: { // field return type name
    confidence_level: 'String'
    entity_id: 'String'
    logo_url: 'String'
    name: 'String'
    type: 'String'
    website: 'String'
  }
  Item: { // field return type name
    auth_method: 'String'
    available_products: 'String'
    billed_products: 'String'
    consent_expiration_time: 'String'
    error: 'String'
    institution_id: 'String'
    institution_name: 'String'
    item_id: 'String'
    update_type: 'String'
    webhook: 'String'
  }
  LinkToken: { // field return type name
    expiration: 'String'
    link_token: 'String'
    request_id: 'String'
  }
  Location: { // field return type name
    address: 'String'
    city: 'String'
    country: 'String'
    lat: 'Float'
    lon: 'Float'
    postal_code: 'String'
    region: 'String'
    store_number: 'String'
  }
  Mutation: { // field return type name
    createLinkToken: 'LinkToken'
    createUser: 'User'
    deleteUser: 'User'
    emailSignIn: 'User'
    exchangePublicToken: 'AccessToken'
    get_balance: 'Any'
    get_transaction_data: 'Any'
    seedTransactions: 'Boolean'
    updateUserDetails: 'User'
  }
  PaymentMeta: { // field return type name
    by_order_of: 'String'
    payee: 'String'
    payer: 'String'
    payment_method: 'String'
    payment_processor: 'String'
    ppd_id: 'String'
    reason: 'String'
    reference_number: 'String'
  }
  PersonalFinanceCategory: { // field return type name
    confidence_level: 'String'
    detailed: 'String'
    primary: 'String'
  }
  Query: { // field return type name
    allTransactions: 'Transaction'
    fetchAccessTokenFromUser: 'AccessToken'
    getTransactionById: 'Transaction'
    getTransactionsByUserId: 'Transaction'
    getuseruidfromuserid: 'uid'
    user: 'User'
    users: 'User'
  }
  Transaction: { // field return type name
    accountName: 'String'
    amount: 'Float'
    category: 'String'
    date: 'Int'
    id: 'Int'
    io: 'InOrOutEnum'
    name: 'String'
    reference: 'String'
    senderOrRecipientName: 'String'
    userId: 'Int'
  }
  TransactionRes: { // field return type name
    accounts: 'Account'
    item: 'Item'
    request_id: 'String'
    total_transactions: 'Int'
    transactions: 'Transaction'
  }
  User: { // field return type name
    email: 'String'
    firstName: 'String'
    id: 'Int'
    lastName: 'String'
    password: 'String'
    phone: 'String'
    transactions: 'Transaction'
    uid: 'String'
    username: 'String'
  }
  uid: { // field return type name
    uid: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createUser: { // args
      email: string; // String!
      firstName?: string | null; // String
      lastName?: string | null; // String
      password?: string | null; // String
      phone?: string | null; // String
      uid: string; // String!
      username: string; // String!
    }
    deleteUser: { // args
      id: number; // Int!
    }
    emailSignIn: { // args
      password: string; // String!
      username: string; // String!
    }
    exchangePublicToken: { // args
      public_token: string; // String!
      userId: string; // String!
    }
    get_balance: { // args
      access_token: string; // String!
    }
    get_transaction_data: { // args
      access_token: string; // String!
      end_date: string; // String!
      start_date: string; // String!
    }
    seedTransactions: { // args
      userId: number; // Int!
    }
    updateUserDetails: { // args
      email: string; // String!
      firstName?: string | null; // String
      id: number; // Int!
      lastName?: string | null; // String
      password?: string | null; // String
      phone?: string | null; // String
      uid: string; // String!
      username: string; // String!
    }
  }
  Query: {
    fetchAccessTokenFromUser: { // args
      userId: number; // Int!
    }
    getTransactionById: { // args
      id: number; // Int!
    }
    getTransactionsByUserId: { // args
      userId: number; // Int!
    }
    getuseruidfromuserid: { // args
      userId: number; // Int!
    }
    user: { // args
      uid: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}